delete from Languages;

insert into Languages (lang_id, question, answer, language, questionNumber) values (0, '﻿adverb tid', 'adverbs of time', 'norwegian', 1);
insert into Languages (lang_id, question, answer, language, questionNumber) values (1, 'i går', 'yesterday', 'norwegian', 2);
insert into Languages (lang_id, question, answer, language, questionNumber) values (2, 'i dag', 'today', 'norwegian', 3);
insert into Languages (lang_id, question, answer, language, questionNumber) values (3, 'i morgen', 'tomorrow', 'norwegian', 4);
insert into Languages (lang_id, question, answer, language, questionNumber) values (4, 'nå', 'now', 'norwegian', 5);
insert into Languages (lang_id, question, answer, language, questionNumber) values (5, 'da', 'then', 'norwegian', 6);
insert into Languages (lang_id, question, answer, language, questionNumber) values (6, 'senere', 'later', 'norwegian', 7);
insert into Languages (lang_id, question, answer, language, questionNumber) values (7, 'i kveld', 'tonight', 'norwegian', 8);
insert into Languages (lang_id, question, answer, language, questionNumber) values (8, 'akkurat nå', 'right now', 'norwegian', 9);
insert into Languages (lang_id, question, answer, language, questionNumber) values (9, 'går kveld', 'last night', 'norwegian', 10);
insert into Languages (lang_id, question, answer, language, questionNumber) values (10, 'i morges', 'this morning', 'norwegian', 11);
insert into Languages (lang_id, question, answer, language, questionNumber) values (11, 'neste uke', 'next week', 'norwegian', 12);
insert into Languages (lang_id, question, answer, language, questionNumber) values (12, 'allerede', 'already', 'norwegian', 13);
insert into Languages (lang_id, question, answer, language, questionNumber) values (13, 'nylig', 'recently', 'norwegian', 14);
insert into Languages (lang_id, question, answer, language, questionNumber) values (14, 'i det siste', 'lately', 'norwegian', 15);
insert into Languages (lang_id, question, answer, language, questionNumber) values (15, 'snart', 'soon', 'norwegian', 16);
insert into Languages (lang_id, question, answer, language, questionNumber) values (16, 'umiddelbart', 'immediately', 'norwegian', 17);
insert into Languages (lang_id, question, answer, language, questionNumber) values (17, 'fortsatt', 'still', 'norwegian', 18);
insert into Languages (lang_id, question, answer, language, questionNumber) values (18, 'ennå', 'yet', 'norwegian', 19);
insert into Languages (lang_id, question, answer, language, questionNumber) values (19, 'siden', 'ago', 'norwegian', 20);
insert into Languages (lang_id, question, answer, language, questionNumber) values (20, 'adverb sted', 'adverbs of place', 'norwegian', 21);
insert into Languages (lang_id, question, answer, language, questionNumber) values (21, 'her', 'here', 'norwegian', 22);
insert into Languages (lang_id, question, answer, language, questionNumber) values (22, 'der', 'there', 'norwegian', 23);
insert into Languages (lang_id, question, answer, language, questionNumber) values (23, 'der borte', 'over there', 'norwegian', 24);
insert into Languages (lang_id, question, answer, language, questionNumber) values (24, 'overalt', 'everywhere', 'norwegian', 25);
insert into Languages (lang_id, question, answer, language, questionNumber) values (25, 'hvor som helst', 'anywhere', 'norwegian', 26);
insert into Languages (lang_id, question, answer, language, questionNumber) values (26, 'ingensteds', 'nowhere', 'norwegian', 27);
insert into Languages (lang_id, question, answer, language, questionNumber) values (27, 'hjem', 'home', 'norwegian', 28);
insert into Languages (lang_id, question, answer, language, questionNumber) values (28, 'borte', 'away', 'norwegian', 29);
insert into Languages (lang_id, question, answer, language, questionNumber) values (29, 'ute', 'out', 'norwegian', 30);
insert into Languages (lang_id, question, answer, language, questionNumber) values (30, 'adverb av måten', 'adverbs of manner', 'norwegian', 31);
insert into Languages (lang_id, question, answer, language, questionNumber) values (31, 'veldig', 'very', 'norwegian', 32);
insert into Languages (lang_id, question, answer, language, questionNumber) values (32, 'veldig/svært/meget', 'quite', 'norwegian', 33);
insert into Languages (lang_id, question, answer, language, questionNumber) values (33, 'pen', 'pretty', 'norwegian', 34);
insert into Languages (lang_id, question, answer, language, questionNumber) values (34, 'virkelig', 'really', 'norwegian', 35);
insert into Languages (lang_id, question, answer, language, questionNumber) values (35, 'rask', 'fast', 'norwegian', 36);
insert into Languages (lang_id, question, answer, language, questionNumber) values (36, 'godt', 'well', 'norwegian', 37);
insert into Languages (lang_id, question, answer, language, questionNumber) values (37, 'hard', 'hard', 'norwegian', 38);
insert into Languages (lang_id, question, answer, language, questionNumber) values (38, 'raskt', 'quickly', 'norwegian', 39);
insert into Languages (lang_id, question, answer, language, questionNumber) values (39, 'sakte', 'slowly', 'norwegian', 40);
insert into Languages (lang_id, question, answer, language, questionNumber) values (40, 'forsiktig', 'carefully', 'norwegian', 41);
insert into Languages (lang_id, question, answer, language, questionNumber) values (41, 'knapt', 'hardly', 'norwegian', 42);
insert into Languages (lang_id, question, answer, language, questionNumber) values (42, 'såvidt', 'barely', 'norwegian', 43);
insert into Languages (lang_id, question, answer, language, questionNumber) values (43, 'for det meste', 'mostly', 'norwegian', 44);
insert into Languages (lang_id, question, answer, language, questionNumber) values (44, 'nesten', 'almost', 'norwegian', 45);
insert into Languages (lang_id, question, answer, language, questionNumber) values (45, 'absolutt', 'absolutely', 'norwegian', 46);
insert into Languages (lang_id, question, answer, language, questionNumber) values (46, 'sammen', 'together', 'norwegian', 47);
insert into Languages (lang_id, question, answer, language, questionNumber) values (47, 'alene', 'alone', 'norwegian', 48);
insert into Languages (lang_id, question, answer, language, questionNumber) values (48, 'tidsadverb', 'adverbs of frequency', 'norwegian', 49);
insert into Languages (lang_id, question, answer, language, questionNumber) values (49, 'alltid', 'always', 'norwegian', 50);
insert into Languages (lang_id, question, answer, language, questionNumber) values (50, 'ofte', 'frequently', 'norwegian', 51);
insert into Languages (lang_id, question, answer, language, questionNumber) values (51, 'vanligvis', 'usually', 'norwegian', 52);
insert into Languages (lang_id, question, answer, language, questionNumber) values (52, 'noen ganger', 'sometimes', 'norwegian', 53);
insert into Languages (lang_id, question, answer, language, questionNumber) values (53, 'en gang i blandt', 'occasionally', 'norwegian', 54);
insert into Languages (lang_id, question, answer, language, questionNumber) values (54, 'sjelden', 'seldom', 'norwegian', 55);
insert into Languages (lang_id, question, answer, language, questionNumber) values (55, 'sjelden', 'rarely', 'norwegian', 56);
insert into Languages (lang_id, question, answer, language, questionNumber) values (56, 'aldri', 'never', 'norwegian', 57);
insert into Languages (lang_id, question, answer, language, questionNumber) values (57, 'Verb', 'Verbs', 'norwegian', 58);
insert into Languages (lang_id, question, answer, language, questionNumber) values (58, 'Fortid', 'Past', 'norwegian', 59);
insert into Languages (lang_id, question, answer, language, questionNumber) values (59, 'Jeg snakket', 'I spoke', 'norwegian', 60);
insert into Languages (lang_id, question, answer, language, questionNumber) values (60, 'Jeg skrev', 'I wrote', 'norwegian', 61);
insert into Languages (lang_id, question, answer, language, questionNumber) values (61, 'Jeg kjørte', 'I drove', 'norwegian', 62);
insert into Languages (lang_id, question, answer, language, questionNumber) values (62, 'Jeg elsket', 'I loved', 'norwegian', 63);
insert into Languages (lang_id, question, answer, language, questionNumber) values (63, 'Jeg ga', 'I gave', 'norwegian', 64);
insert into Languages (lang_id, question, answer, language, questionNumber) values (64, 'Jeg smilte', 'I smiled', 'norwegian', 65);
insert into Languages (lang_id, question, answer, language, questionNumber) values (65, 'Jeg tok', 'I took', 'norwegian', 66);
insert into Languages (lang_id, question, answer, language, questionNumber) values (66, 'Han snakket', 'he spoke', 'norwegian', 67);
insert into Languages (lang_id, question, answer, language, questionNumber) values (67, 'han skrev', 'he wrote', 'norwegian', 68);
insert into Languages (lang_id, question, answer, language, questionNumber) values (68, 'Han kjørte', 'he drove', 'norwegian', 69);
insert into Languages (lang_id, question, answer, language, questionNumber) values (69, 'Han elsket', 'he loved', 'norwegian', 70);
insert into Languages (lang_id, question, answer, language, questionNumber) values (70, 'Han ga', 'he gave', 'norwegian', 71);
insert into Languages (lang_id, question, answer, language, questionNumber) values (71, 'Han smilte', 'he smiled', 'norwegian', 72);
insert into Languages (lang_id, question, answer, language, questionNumber) values (72, 'han tok', 'he took', 'norwegian', 73);
insert into Languages (lang_id, question, answer, language, questionNumber) values (73, 'vi snakket', 'we spoke', 'norwegian', 74);
insert into Languages (lang_id, question, answer, language, questionNumber) values (74, 'vi skrev', 'we wrote', 'norwegian', 75);
insert into Languages (lang_id, question, answer, language, questionNumber) values (75, 'vi kjørte', 'we drove', 'norwegian', 76);
insert into Languages (lang_id, question, answer, language, questionNumber) values (76, 'vi elsket', 'we loved', 'norwegian', 77);
insert into Languages (lang_id, question, answer, language, questionNumber) values (77, 'Vi ga', 'we gave', 'norwegian', 78);
insert into Languages (lang_id, question, answer, language, questionNumber) values (78, 'vi smilte', 'we smiled', 'norwegian', 79);
insert into Languages (lang_id, question, answer, language, questionNumber) values (79, 'vi tok', 'we took', 'norwegian', 80);
insert into Languages (lang_id, question, answer, language, questionNumber) values (80, 'Fremtid', 'Future', 'norwegian', 81);
insert into Languages (lang_id, question, answer, language, questionNumber) values (81, 'Jeg kommer til å snakke', 'I will speak', 'norwegian', 82);
insert into Languages (lang_id, question, answer, language, questionNumber) values (82, 'Jeg vil skrive', 'I will write', 'norwegian', 83);
insert into Languages (lang_id, question, answer, language, questionNumber) values (83, 'Jeg vil kjøre', 'I will drive', 'norwegian', 84);
insert into Languages (lang_id, question, answer, language, questionNumber) values (84, 'Jeg vil elske', 'I will love', 'norwegian', 85);
insert into Languages (lang_id, question, answer, language, questionNumber) values (85, 'Jeg vil gi', 'I will give', 'norwegian', 86);
insert into Languages (lang_id, question, answer, language, questionNumber) values (86, 'Jeg vil smile', 'I will smile', 'norwegian', 87);
insert into Languages (lang_id, question, answer, language, questionNumber) values (87, 'Jeg vil ta', 'I will take', 'norwegian', 88);
insert into Languages (lang_id, question, answer, language, questionNumber) values (88, 'han vil snakke', 'he will speak', 'norwegian', 89);
insert into Languages (lang_id, question, answer, language, questionNumber) values (89, 'han vil skrive', 'he will write', 'norwegian', 90);
insert into Languages (lang_id, question, answer, language, questionNumber) values (90, 'han vil drive', 'he will drive', 'norwegian', 91);
insert into Languages (lang_id, question, answer, language, questionNumber) values (91, 'han vil elske', 'he will love', 'norwegian', 92);
insert into Languages (lang_id, question, answer, language, questionNumber) values (92, 'Han vil gi', 'he will give', 'norwegian', 93);
insert into Languages (lang_id, question, answer, language, questionNumber) values (93, 'han vil smile', 'he will smile', 'norwegian', 94);
insert into Languages (lang_id, question, answer, language, questionNumber) values (94, 'han vil ta', 'he will take', 'norwegian', 95);
insert into Languages (lang_id, question, answer, language, questionNumber) values (95, 'vi vil snakke', 'we will speak', 'norwegian', 96);
insert into Languages (lang_id, question, answer, language, questionNumber) values (96, 'vi vil skrive', 'we will write', 'norwegian', 97);
insert into Languages (lang_id, question, answer, language, questionNumber) values (97, 'vi vil kjøre', 'we will drive', 'norwegian', 98);
insert into Languages (lang_id, question, answer, language, questionNumber) values (98, 'vi vil elske', 'we will love', 'norwegian', 99);
insert into Languages (lang_id, question, answer, language, questionNumber) values (99, 'vi vil gi', 'we will give', 'norwegian', 100);
insert into Languages (lang_id, question, answer, language, questionNumber) values (100, 'vi vil smile', 'we will smile', 'norwegian', 101);
insert into Languages (lang_id, question, answer, language, questionNumber) values (101, 'vi vil ta', 'we will take', 'norwegian', 102);
insert into Languages (lang_id, question, answer, language, questionNumber) values (102, 'Nåtid', 'Present', 'norwegian', 103);
insert into Languages (lang_id, question, answer, language, questionNumber) values (103, 'Jeg snakker', 'I speak', 'norwegian', 104);
insert into Languages (lang_id, question, answer, language, questionNumber) values (104, 'Jeg skriver', 'I write', 'norwegian', 105);
insert into Languages (lang_id, question, answer, language, questionNumber) values (105, 'Jeg kjører', 'I drive', 'norwegian', 106);
insert into Languages (lang_id, question, answer, language, questionNumber) values (106, 'Jeg elsker', 'I love', 'norwegian', 107);
insert into Languages (lang_id, question, answer, language, questionNumber) values (107, 'Jeg gir', 'I give', 'norwegian', 108);
insert into Languages (lang_id, question, answer, language, questionNumber) values (108, 'Jeg smiler', 'I smile', 'norwegian', 109);
insert into Languages (lang_id, question, answer, language, questionNumber) values (109, 'Jeg tar', 'I take', 'norwegian', 110);
insert into Languages (lang_id, question, answer, language, questionNumber) values (110, 'han snakker', 'he speaks', 'norwegian', 111);
insert into Languages (lang_id, question, answer, language, questionNumber) values (111, 'han skriver', 'he writes', 'norwegian', 112);
insert into Languages (lang_id, question, answer, language, questionNumber) values (112, 'han kjører', 'he drives', 'norwegian', 113);
insert into Languages (lang_id, question, answer, language, questionNumber) values (113, 'han elsker', 'he loves', 'norwegian', 114);
insert into Languages (lang_id, question, answer, language, questionNumber) values (114, 'Han gir', 'he gives', 'norwegian', 115);
insert into Languages (lang_id, question, answer, language, questionNumber) values (115, 'han smiler', 'he smiles', 'norwegian', 116);
insert into Languages (lang_id, question, answer, language, questionNumber) values (116, 'Han tar', 'he takes', 'norwegian', 117);
insert into Languages (lang_id, question, answer, language, questionNumber) values (117, 'vi snakker', 'we speak', 'norwegian', 118);
insert into Languages (lang_id, question, answer, language, questionNumber) values (118, 'vi skriver', 'we write', 'norwegian', 119);
insert into Languages (lang_id, question, answer, language, questionNumber) values (119, 'vi kjører', 'we drive', 'norwegian', 120);
insert into Languages (lang_id, question, answer, language, questionNumber) values (120, 'vi elsker', 'we love', 'norwegian', 121);
insert into Languages (lang_id, question, answer, language, questionNumber) values (121, 'vi gir', 'we give', 'norwegian', 122);
insert into Languages (lang_id, question, answer, language, questionNumber) values (122, 'vi smile', 'we smile', 'norwegian', 123);
insert into Languages (lang_id, question, answer, language, questionNumber) values (123, 'vi tar', 'we take', 'norwegian', 124);
insert into Languages (lang_id, question, answer, language, questionNumber) values (124, '﻿Buenos días', 'Good morning', 'spanish', 1);
insert into Languages (lang_id, question, answer, language, questionNumber) values (125, 'Buenas tardes', 'Good afternoon', 'spanish', 2);
insert into Languages (lang_id, question, answer, language, questionNumber) values (126, 'Buenas noches', 'Good evening', 'spanish', 3);
insert into Languages (lang_id, question, answer, language, questionNumber) values (127, '"Hola, me llamo Juan"', '"Hello, my name is John"', 'spanish', 4);
insert into Languages (lang_id, question, answer, language, questionNumber) values (128, '¿Cómo se llama usted?', 'What is your name?', 'spanish', 5);
insert into Languages (lang_id, question, answer, language, questionNumber) values (129, '¿Cómo está usted?', 'How are you?', 'spanish', 6);
insert into Languages (lang_id, question, answer, language, questionNumber) values (130, 'Estoy bien', 'I am fine', 'spanish', 7);
insert into Languages (lang_id, question, answer, language, questionNumber) values (131, 'Mucho gusto', 'Nice to meet you', 'spanish', 8);
insert into Languages (lang_id, question, answer, language, questionNumber) values (132, 'Adiós', 'Goodbye', 'spanish', 9);
insert into Languages (lang_id, question, answer, language, questionNumber) values (133, 'Hasta luego', 'See you later', 'spanish', 10);
insert into Languages (lang_id, question, answer, language, questionNumber) values (134, 'Estoy perdido. ¿Dónde está el baño?', 'I am lost. Where is the restroom?', 'spanish', 11);
insert into Languages (lang_id, question, answer, language, questionNumber) values (135, 'Con permiso. OR Perdóname', 'Excuse me', 'spanish', 12);
insert into Languages (lang_id, question, answer, language, questionNumber) values (136, 'Por favor', 'Please', 'spanish', 13);
insert into Languages (lang_id, question, answer, language, questionNumber) values (137, 'Gracías', 'Thank you', 'spanish', 14);
insert into Languages (lang_id, question, answer, language, questionNumber) values (138, 'Lo siento', 'I''m sorry', 'spanish', 15);
insert into Languages (lang_id, question, answer, language, questionNumber) values (139, 'Salud', 'Bless you', 'spanish', 16);
insert into Languages (lang_id, question, answer, language, questionNumber) values (140, 'De nada', 'You are welcome', 'spanish', 17);
insert into Languages (lang_id, question, answer, language, questionNumber) values (141, '¿Cuánto cuesta?', 'How much does it cost?', 'spanish', 18);
insert into Languages (lang_id, question, answer, language, questionNumber) values (142, '¿Cuántos hay?', 'How many are there?', 'spanish', 19);
insert into Languages (lang_id, question, answer, language, questionNumber) values (143, 'Hay muchos', 'There are many', 'spanish', 20);
insert into Languages (lang_id, question, answer, language, questionNumber) values (144, '¿Quiere comprarlo usted?', 'Do you want to buy this?', 'spanish', 21);
insert into Languages (lang_id, question, answer, language, questionNumber) values (145, '¿Qué hora es?', 'What time is it?', 'spanish', 22);
insert into Languages (lang_id, question, answer, language, questionNumber) values (146, '¿Cómo se dice maybe en Español?', 'How do you say maybe in Spanish?', 'spanish', 23);
insert into Languages (lang_id, question, answer, language, questionNumber) values (147, 'Sí', 'Yes', 'spanish', 24);
insert into Languages (lang_id, question, answer, language, questionNumber) values (148, 'No', 'No', 'spanish', 25);
insert into Languages (lang_id, question, answer, language, questionNumber) values (149, 'Yo no comprendo', 'I do not understand', 'spanish', 26);
insert into Languages (lang_id, question, answer, language, questionNumber) values (150, '"Por favor, habla mas despacio"', '"Would you speak slower, please"', 'spanish', 27);
insert into Languages (lang_id, question, answer, language, questionNumber) values (151, '¿Quièn?', 'Who?', 'spanish', 28);
insert into Languages (lang_id, question, answer, language, questionNumber) values (152, '¿Por què?', 'Why?', 'spanish', 29);
insert into Languages (lang_id, question, answer, language, questionNumber) values (153, 'contabilidad', 'accounting', 'spanish', 30);
insert into Languages (lang_id, question, answer, language, questionNumber) values (154, 'álgebra', 'algebra', 'spanish', 31);
insert into Languages (lang_id, question, answer, language, questionNumber) values (155, 'arte', 'art', 'spanish', 32);
insert into Languages (lang_id, question, answer, language, questionNumber) values (156, 'biología', 'biology', 'spanish', 33);
insert into Languages (lang_id, question, answer, language, questionNumber) values (157, 'negocio', 'business', 'spanish', 34);
insert into Languages (lang_id, question, answer, language, questionNumber) values (158, 'cálculo', 'calculus', 'spanish', 35);
insert into Languages (lang_id, question, answer, language, questionNumber) values (159, 'química', 'chemistry', 'spanish', 36);
insert into Languages (lang_id, question, answer, language, questionNumber) values (160, 'informática', 'computer science', 'spanish', 37);
insert into Languages (lang_id, question, answer, language, questionNumber) values (161, 'danza', 'dance', 'spanish', 38);
insert into Languages (lang_id, question, answer, language, questionNumber) values (162, 'economía', 'economics', 'spanish', 39);
insert into Languages (lang_id, question, answer, language, questionNumber) values (163, 'idiomas extranjeros', 'foreign languages', 'spanish', 40);
insert into Languages (lang_id, question, answer, language, questionNumber) values (164, 'geografía', 'geography', 'spanish', 41);
insert into Languages (lang_id, question, answer, language, questionNumber) values (165, 'geometría', 'geometry', 'spanish', 42);
insert into Languages (lang_id, question, answer, language, questionNumber) values (166, 'historia', 'history', 'spanish', 43);
insert into Languages (lang_id, question, answer, language, questionNumber) values (167, 'matemáticas', 'math', 'spanish', 44);
insert into Languages (lang_id, question, answer, language, questionNumber) values (168, 'música', 'music', 'spanish', 45);
insert into Languages (lang_id, question, answer, language, questionNumber) values (169, 'educación física', 'physical education', 'spanish', 46);
insert into Languages (lang_id, question, answer, language, questionNumber) values (170, 'física', 'physics', 'spanish', 47);
insert into Languages (lang_id, question, answer, language, questionNumber) values (171, 'ciencia política', 'political science', 'spanish', 48);
insert into Languages (lang_id, question, answer, language, questionNumber) values (172, 'el libro', 'book', 'spanish', 49);
insert into Languages (lang_id, question, answer, language, questionNumber) values (173, 'el colegio', 'college', 'spanish', 50);
insert into Languages (lang_id, question, answer, language, questionNumber) values (174, 'la computadora', 'computer', 'spanish', 51);
insert into Languages (lang_id, question, answer, language, questionNumber) values (175, 'el diccionário', 'dictionary', 'spanish', 52);
insert into Languages (lang_id, question, answer, language, questionNumber) values (176, 'el papel', 'paper', 'spanish', 53);
insert into Languages (lang_id, question, answer, language, questionNumber) values (177, 'el lapiz', 'pencil', 'spanish', 54);
insert into Languages (lang_id, question, answer, language, questionNumber) values (178, 'el lapicero', 'pen', 'spanish', 55);
insert into Languages (lang_id, question, answer, language, questionNumber) values (179, 'profesor/a', 'professor', 'spanish', 56);
insert into Languages (lang_id, question, answer, language, questionNumber) values (180, 'escuela', 'school', 'spanish', 57);
insert into Languages (lang_id, question, answer, language, questionNumber) values (181, 'estudiente', 'student', 'spanish', 58);
insert into Languages (lang_id, question, answer, language, questionNumber) values (182, 'maestro/maestra', 'teacher', 'spanish', 59);
insert into Languages (lang_id, question, answer, language, questionNumber) values (183, 'el examen', 'test/quiz/exam', 'spanish', 60);
insert into Languages (lang_id, question, answer, language, questionNumber) values (184, 'la universidad', 'university', 'spanish', 61);
insert into Languages (lang_id, question, answer, language, questionNumber) values (185, 'estudiar', 'to study', 'spanish', 62);
insert into Languages (lang_id, question, answer, language, questionNumber) values (186, 'aprender', 'to learn', 'spanish', 63);
insert into Languages (lang_id, question, answer, language, questionNumber) values (187, 'enseñar', 'to teach', 'spanish', 64);
insert into Languages (lang_id, question, answer, language, questionNumber) values (188, 'escribir', 'to write', 'spanish', 65);
insert into Languages (lang_id, question, answer, language, questionNumber) values (189, 'dibujar', 'to draw', 'spanish', 66);
insert into Languages (lang_id, question, answer, language, questionNumber) values (190, 'leer', 'to read', 'spanish', 67);
insert into Languages (lang_id, question, answer, language, questionNumber) values (191, 'el aeropuerto', 'airport', 'spanish', 68);
insert into Languages (lang_id, question, answer, language, questionNumber) values (192, 'lapanadería', 'bakery', 'spanish', 69);
insert into Languages (lang_id, question, answer, language, questionNumber) values (193, 'el banco', 'bank', 'spanish', 70);
insert into Languages (lang_id, question, answer, language, questionNumber) values (194, 'la playa', 'beach', 'spanish', 71);
insert into Languages (lang_id, question, answer, language, questionNumber) values (195, 'el café', 'cafe', 'spanish', 72);
insert into Languages (lang_id, question, answer, language, questionNumber) values (196, 'la iglesia', 'church', 'spanish', 73);
insert into Languages (lang_id, question, answer, language, questionNumber) values (197, 'la fábrica', 'factory', 'spanish', 74);
insert into Languages (lang_id, question, answer, language, questionNumber) values (198, 'el gardín', 'garden', 'spanish', 75);
insert into Languages (lang_id, question, answer, language, questionNumber) values (199, 'almacén', 'grocery store', 'spanish', 76);
insert into Languages (lang_id, question, answer, language, questionNumber) values (200, 'el hogar', 'home', 'spanish', 77);
insert into Languages (lang_id, question, answer, language, questionNumber) values (201, 'la hospital', 'hospital', 'spanish', 78);
insert into Languages (lang_id, question, answer, language, questionNumber) values (202, 'la biblioteca', 'library', 'spanish', 79);
insert into Languages (lang_id, question, answer, language, questionNumber) values (203, 'el mercado', 'market', 'spanish', 80);
insert into Languages (lang_id, question, answer, language, questionNumber) values (204, 'el cine', 'movie theater', 'spanish', 81);
insert into Languages (lang_id, question, answer, language, questionNumber) values (205, 'el museo', 'museum', 'spanish', 82);
insert into Languages (lang_id, question, answer, language, questionNumber) values (206, 'panaderia', 'pastry shop', 'spanish', 83);
insert into Languages (lang_id, question, answer, language, questionNumber) values (207, 'el parque', 'park', 'spanish', 84);
insert into Languages (lang_id, question, answer, language, questionNumber) values (208, 'la farmácia', 'pharmacy', 'spanish', 85);
insert into Languages (lang_id, question, answer, language, questionNumber) values (209, 'la estación de la policía', 'police station', 'spanish', 86);
insert into Languages (lang_id, question, answer, language, questionNumber) values (210, 'los correos', 'post office', 'spanish', 87);
insert into Languages (lang_id, question, answer, language, questionNumber) values (211, 'la piscina', 'pool', 'spanish', 88);
insert into Languages (lang_id, question, answer, language, questionNumber) values (212, 'el restaurante', 'restaurant', 'spanish', 89);
insert into Languages (lang_id, question, answer, language, questionNumber) values (213, 'la escuela', 'school', 'spanish', 90);
insert into Languages (lang_id, question, answer, language, questionNumber) values (214, 'el estadio', 'stadium', 'spanish', 91);
insert into Languages (lang_id, question, answer, language, questionNumber) values (215, 'tienda', 'store', 'spanish', 92);
insert into Languages (lang_id, question, answer, language, questionNumber) values (216, 'la estación del tren', 'train station', 'spanish', 93);
insert into Languages (lang_id, question, answer, language, questionNumber) values (217, 'pasillo de ciudad', 'town hall', 'spanish', 94);
insert into Languages (lang_id, question, answer, language, questionNumber) values (218, 'librería', 'bookstore', 'spanish', 95);
insert into Languages (lang_id, question, answer, language, questionNumber) values (219, 'parque zoológico', 'zoo', 'spanish', 96);
insert into Languages (lang_id, question, answer, language, questionNumber) values (220, 'la officina', 'office', 'spanish', 97);
insert into Languages (lang_id, question, answer, language, questionNumber) values (221, 'la ciudad', 'city', 'spanish', 98);
insert into Languages (lang_id, question, answer, language, questionNumber) values (222, 'la renta', 'the rent', 'spanish', 99);
insert into Languages (lang_id, question, answer, language, questionNumber) values (223, 'el impuesto', 'tax', 'spanish', 100);
insert into Languages (lang_id, question, answer, language, questionNumber) values (224, 'la cuesta', 'the cost', 'spanish', 101);
insert into Languages (lang_id, question, answer, language, questionNumber) values (225, 'el précio', 'price', 'spanish', 102);
insert into Languages (lang_id, question, answer, language, questionNumber) values (226, 'la cuenta', 'bill', 'spanish', 103);
insert into Languages (lang_id, question, answer, language, questionNumber) values (227, 'la estimación', 'estimate', 'spanish', 104);
insert into Languages (lang_id, question, answer, language, questionNumber) values (228, 'el cheque', 'check', 'spanish', 105);
insert into Languages (lang_id, question, answer, language, questionNumber) values (229, 'el cheque de viajar', 'travelers check', 'spanish', 106);
insert into Languages (lang_id, question, answer, language, questionNumber) values (230, 'el passaporte', 'passport', 'spanish', 107);
insert into Languages (lang_id, question, answer, language, questionNumber) values (231, 'el equipaje', 'luggage', 'spanish', 108);
insert into Languages (lang_id, question, answer, language, questionNumber) values (232, 'el intercambio de modernidad', 'currency exchange', 'spanish', 109);
insert into Languages (lang_id, question, answer, language, questionNumber) values (233, 'las aduanas', 'customs', 'spanish', 110);
insert into Languages (lang_id, question, answer, language, questionNumber) values (234, 'la entrada', 'entrance', 'spanish', 111);
insert into Languages (lang_id, question, answer, language, questionNumber) values (235, 'el salido', 'exit', 'spanish', 112);
insert into Languages (lang_id, question, answer, language, questionNumber) values (236, 'la información', 'information', 'spanish', 113);
insert into Languages (lang_id, question, answer, language, questionNumber) values (237, 'pagar', 'to pay', 'spanish', 114);
insert into Languages (lang_id, question, answer, language, questionNumber) values (238, 'comprar', 'to buy', 'spanish', 115);
insert into Languages (lang_id, question, answer, language, questionNumber) values (239, 'vender', 'to sell', 'spanish', 116);
insert into Languages (lang_id, question, answer, language, questionNumber) values (240, 'costar', 'to cost', 'spanish', 117);
insert into Languages (lang_id, question, answer, language, questionNumber) values (241, 'alquiler', 'to rent', 'spanish', 118);
insert into Languages (lang_id, question, answer, language, questionNumber) values (242, 'depositar', 'to deposit', 'spanish', 119);
insert into Languages (lang_id, question, answer, language, questionNumber) values (243, 'en avión', 'by airplane', 'spanish', 120);
insert into Languages (lang_id, question, answer, language, questionNumber) values (244, 'en bicicleta', 'by bicycle', 'spanish', 121);
insert into Languages (lang_id, question, answer, language, questionNumber) values (245, 'en barco', 'by boat', 'spanish', 122);
insert into Languages (lang_id, question, answer, language, questionNumber) values (246, 'en bus', 'by bus', 'spanish', 123);
insert into Languages (lang_id, question, answer, language, questionNumber) values (247, 'en automovíl', 'by car', 'spanish', 124);
insert into Languages (lang_id, question, answer, language, questionNumber) values (248, 'a pie', 'on foot', 'spanish', 125);
insert into Languages (lang_id, question, answer, language, questionNumber) values (249, 'en ciclomotor', 'by moped', 'spanish', 126);
insert into Languages (lang_id, question, answer, language, questionNumber) values (250, 'en motocicleta', 'by motorcycle', 'spanish', 127);
insert into Languages (lang_id, question, answer, language, questionNumber) values (251, 'en subterráneo', 'by subway', 'spanish', 128);
insert into Languages (lang_id, question, answer, language, questionNumber) values (252, 'en taxi', 'by taxi', 'spanish', 129);
insert into Languages (lang_id, question, answer, language, questionNumber) values (253, 'en tren', 'by train', 'spanish', 130);
insert into Languages (lang_id, question, answer, language, questionNumber) values (254, 'motor', 'engine', 'spanish', 131);
insert into Languages (lang_id, question, answer, language, questionNumber) values (255, 'llanta', 'wheel', 'spanish', 132);
insert into Languages (lang_id, question, answer, language, questionNumber) values (256, 'mapa', 'map', 'spanish', 133);
insert into Languages (lang_id, question, answer, language, questionNumber) values (257, 'los direcciones', 'directions', 'spanish', 134);
insert into Languages (lang_id, question, answer, language, questionNumber) values (258, 'acelerar', 'to accelerate', 'spanish', 135);
insert into Languages (lang_id, question, answer, language, questionNumber) values (259, 'retardarse', 'to break', 'spanish', 136);
insert into Languages (lang_id, question, answer, language, questionNumber) values (260, 'parar', 'to stop', 'spanish', 137);
insert into Languages (lang_id, question, answer, language, questionNumber) values (261, 'ir', 'to go', 'spanish', 138);
insert into Languages (lang_id, question, answer, language, questionNumber) values (262, 'dar vuelta a la izqierda', 'turn left', 'spanish', 139);
insert into Languages (lang_id, question, answer, language, questionNumber) values (263, 'dar vuelta a la derecha', 'turn right', 'spanish', 140);
insert into Languages (lang_id, question, answer, language, questionNumber) values (264, 'ir derecho', 'go straight', 'spanish', 141);
insert into Languages (lang_id, question, answer, language, questionNumber) values (265, 'la casa', 'house', 'spanish', 142);
insert into Languages (lang_id, question, answer, language, questionNumber) values (266, 'el apartamento', 'apartment', 'spanish', 143);
insert into Languages (lang_id, question, answer, language, questionNumber) values (267, 'el cuarto', 'room', 'spanish', 144);
insert into Languages (lang_id, question, answer, language, questionNumber) values (268, 'la sala', 'living room', 'spanish', 145);
insert into Languages (lang_id, question, answer, language, questionNumber) values (269, 'la cocina', 'kitchen', 'spanish', 146);
insert into Languages (lang_id, question, answer, language, questionNumber) values (270, 'cuarto de cenar', 'dining room', 'spanish', 147);
insert into Languages (lang_id, question, answer, language, questionNumber) values (271, 'vestíbulo', 'hallway', 'spanish', 148);
insert into Languages (lang_id, question, answer, language, questionNumber) values (272, 'escaleras', 'stairs', 'spanish', 149);
insert into Languages (lang_id, question, answer, language, questionNumber) values (273, 'el baño', 'bathroom', 'spanish', 150);
insert into Languages (lang_id, question, answer, language, questionNumber) values (274, 'bañera', 'bathtub', 'spanish', 151);
insert into Languages (lang_id, question, answer, language, questionNumber) values (275, 'ducha', 'shower', 'spanish', 152);
insert into Languages (lang_id, question, answer, language, questionNumber) values (276, 'la pila', 'sink', 'spanish', 153);
insert into Languages (lang_id, question, answer, language, questionNumber) values (277, 'azotea', 'roof', 'spanish', 154);
insert into Languages (lang_id, question, answer, language, questionNumber) values (278, 'armario', 'closet', 'spanish', 155);
insert into Languages (lang_id, question, answer, language, questionNumber) values (279, 'la ventana', 'window', 'spanish', 156);
insert into Languages (lang_id, question, answer, language, questionNumber) values (280, 'la pared', 'wall', 'spanish', 157);
insert into Languages (lang_id, question, answer, language, questionNumber) values (281, 'la mesa', 'table', 'spanish', 158);
insert into Languages (lang_id, question, answer, language, questionNumber) values (282, 'la silla', 'chair', 'spanish', 159);
insert into Languages (lang_id, question, answer, language, questionNumber) values (283, 'sofá', 'couch', 'spanish', 160);
insert into Languages (lang_id, question, answer, language, questionNumber) values (284, 'escritorio', 'desk', 'spanish', 161);
insert into Languages (lang_id, question, answer, language, questionNumber) values (285, 'lavaplatos', 'dishwasher', 'spanish', 162);
insert into Languages (lang_id, question, answer, language, questionNumber) values (286, 'el puerto', 'door', 'spanish', 163);
insert into Languages (lang_id, question, answer, language, questionNumber) values (287, 'la luz', 'light', 'spanish', 164);
insert into Languages (lang_id, question, answer, language, questionNumber) values (288, 'cama', 'bed', 'spanish', 165);
insert into Languages (lang_id, question, answer, language, questionNumber) values (289, 'manta', 'blanket', 'spanish', 166);
insert into Languages (lang_id, question, answer, language, questionNumber) values (290, 'televisión', 'television', 'spanish', 167);
insert into Languages (lang_id, question, answer, language, questionNumber) values (291, 'el rádio', 'radio', 'spanish', 168);
insert into Languages (lang_id, question, answer, language, questionNumber) values (292, 'la refrijedora', 'refrigerator', 'spanish', 169);
insert into Languages (lang_id, question, answer, language, questionNumber) values (293, 'estufa', 'stove', 'spanish', 170);
insert into Languages (lang_id, question, answer, language, questionNumber) values (294, 'el horno', 'oven', 'spanish', 171);
insert into Languages (lang_id, question, answer, language, questionNumber) values (295, 'la basura', 'garbage', 'spanish', 172);
insert into Languages (lang_id, question, answer, language, questionNumber) values (296, 'microonda', 'microwave', 'spanish', 173);
insert into Languages (lang_id, question, answer, language, questionNumber) values (297, 'la cabeza', 'head', 'spanish', 174);
insert into Languages (lang_id, question, answer, language, questionNumber) values (298, 'el cerebro', 'brain', 'spanish', 175);
insert into Languages (lang_id, question, answer, language, questionNumber) values (299, 'el pelo', 'hair', 'spanish', 176);
insert into Languages (lang_id, question, answer, language, questionNumber) values (300, 'la cara', 'face', 'spanish', 177);
insert into Languages (lang_id, question, answer, language, questionNumber) values (301, 'el oreja', 'ear', 'spanish', 178);
insert into Languages (lang_id, question, answer, language, questionNumber) values (302, 'el ojo', 'eye', 'spanish', 179);
insert into Languages (lang_id, question, answer, language, questionNumber) values (303, 'la boca', 'mouth', 'spanish', 180);
insert into Languages (lang_id, question, answer, language, questionNumber) values (304, 'la naríz', 'nose', 'spanish', 181);
insert into Languages (lang_id, question, answer, language, questionNumber) values (305, 'el cuello', 'neck', 'spanish', 182);
insert into Languages (lang_id, question, answer, language, questionNumber) values (306, 'el hombro', 'shoulder', 'spanish', 183);
insert into Languages (lang_id, question, answer, language, questionNumber) values (307, 'el pecho', 'chest', 'spanish', 184);
insert into Languages (lang_id, question, answer, language, questionNumber) values (308, 'el estómigo', 'stomach', 'spanish', 185);
insert into Languages (lang_id, question, answer, language, questionNumber) values (309, 'la cintura', 'waist', 'spanish', 186);
insert into Languages (lang_id, question, answer, language, questionNumber) values (310, 'la espalda', 'back', 'spanish', 187);
insert into Languages (lang_id, question, answer, language, questionNumber) values (311, 'el corazón', 'heart', 'spanish', 188);
insert into Languages (lang_id, question, answer, language, questionNumber) values (312, 'el brazo', 'arm', 'spanish', 189);
insert into Languages (lang_id, question, answer, language, questionNumber) values (313, 'el codo', 'elbow', 'spanish', 190);
insert into Languages (lang_id, question, answer, language, questionNumber) values (314, 'la muñeca', 'wrist', 'spanish', 191);
insert into Languages (lang_id, question, answer, language, questionNumber) values (315, 'el mano', 'hand', 'spanish', 192);
insert into Languages (lang_id, question, answer, language, questionNumber) values (316, 'el dedo', 'finger', 'spanish', 193);
insert into Languages (lang_id, question, answer, language, questionNumber) values (317, 'la pierna', 'leg', 'spanish', 194);
insert into Languages (lang_id, question, answer, language, questionNumber) values (318, 'el pie', 'foot', 'spanish', 195);
insert into Languages (lang_id, question, answer, language, questionNumber) values (319, 'el dedo del pie', 'toe', 'spanish', 196);
insert into Languages (lang_id, question, answer, language, questionNumber) values (320, 'el sombrero', 'hat', 'spanish', 197);
insert into Languages (lang_id, question, answer, language, questionNumber) values (321, 'los pendientes', 'earrings', 'spanish', 198);
insert into Languages (lang_id, question, answer, language, questionNumber) values (322, 'la camisa', 'shirt', 'spanish', 199);
insert into Languages (lang_id, question, answer, language, questionNumber) values (323, 'la blusa', 'blouse', 'spanish', 200);
insert into Languages (lang_id, question, answer, language, questionNumber) values (324, 'el vestido', 'dress', 'spanish', 201);
insert into Languages (lang_id, question, answer, language, questionNumber) values (325, 'los pantelones', 'pants', 'spanish', 202);
insert into Languages (lang_id, question, answer, language, questionNumber) values (326, 'pantalones vaqueros', 'jeans', 'spanish', 203);
insert into Languages (lang_id, question, answer, language, questionNumber) values (327, 'la falda', 'skirt', 'spanish', 204);
insert into Languages (lang_id, question, answer, language, questionNumber) values (328, 'los calcetines', 'socks', 'spanish', 205);
insert into Languages (lang_id, question, answer, language, questionNumber) values (329, 'los zapatos', 'shoes', 'spanish', 206);
insert into Languages (lang_id, question, answer, language, questionNumber) values (330, 'el traje de bañar', 'swimsuit', 'spanish', 207);
insert into Languages (lang_id, question, answer, language, questionNumber) values (331, 'ropa anterior', 'underwear', 'spanish', 208);
insert into Languages (lang_id, question, answer, language, questionNumber) values (332, 'los guantes', 'gloves', 'spanish', 209);
insert into Languages (lang_id, question, answer, language, questionNumber) values (333, 'la correa', 'belt', 'spanish', 210);
insert into Languages (lang_id, question, answer, language, questionNumber) values (334, 'la capa', 'coat', 'spanish', 211);
insert into Languages (lang_id, question, answer, language, questionNumber) values (335, 'el anillo', 'ring', 'spanish', 212);
insert into Languages (lang_id, question, answer, language, questionNumber) values (336, 'Me duelle en mi brazo.', 'My arm hurts.', 'spanish', 213);
insert into Languages (lang_id, question, answer, language, questionNumber) values (337, '¿Estás lastimado?', 'Are you hurt?', 'spanish', 214);
insert into Languages (lang_id, question, answer, language, questionNumber) values (338, 'Tengo dolor de la cabeza.', 'I have a headache.', 'spanish', 215);
insert into Languages (lang_id, question, answer, language, questionNumber) values (339, '¿Tienes aspirina?', 'Do you have aspirin?', 'spanish', 216);
insert into Languages (lang_id, question, answer, language, questionNumber) values (340, 'Me estás lastimando.', 'You are hurting me.', 'spanish', 217);
insert into Languages (lang_id, question, answer, language, questionNumber) values (341, 'No lo/la lastimas.', 'Don''t hurt him/her.', 'spanish', 218);
insert into Languages (lang_id, question, answer, language, questionNumber) values (342, 'perro/a', 'dog', 'spanish', 219);
insert into Languages (lang_id, question, answer, language, questionNumber) values (343, 'gato/a', 'cat', 'spanish', 220);
insert into Languages (lang_id, question, answer, language, questionNumber) values (344, 'ratón', 'mouse', 'spanish', 221);
insert into Languages (lang_id, question, answer, language, questionNumber) values (345, 'ave', 'bird', 'spanish', 222);
insert into Languages (lang_id, question, answer, language, questionNumber) values (346, 'gallina/gallo', 'chicken/rooster', 'spanish', 223);
insert into Languages (lang_id, question, answer, language, questionNumber) values (347, 'la vaca', 'cow', 'spanish', 224);
insert into Languages (lang_id, question, answer, language, questionNumber) values (348, 'pato/a', 'duck', 'spanish', 225);
insert into Languages (lang_id, question, answer, language, questionNumber) values (349, 'la cabra', 'goat', 'spanish', 226);
insert into Languages (lang_id, question, answer, language, questionNumber) values (350, 'el caballo', 'horse', 'spanish', 227);
insert into Languages (lang_id, question, answer, language, questionNumber) values (351, 'cerdo/a', 'pig', 'spanish', 228);
insert into Languages (lang_id, question, answer, language, questionNumber) values (352, 'oveja', 'sheep', 'spanish', 229);
insert into Languages (lang_id, question, answer, language, questionNumber) values (353, 'el lión', 'lion', 'spanish', 230);
insert into Languages (lang_id, question, answer, language, questionNumber) values (354, 'el tigre', 'tiger', 'spanish', 231);
insert into Languages (lang_id, question, answer, language, questionNumber) values (355, 'el oso', 'bear', 'spanish', 232);
insert into Languages (lang_id, question, answer, language, questionNumber) values (356, 'el lobo', 'wolf', 'spanish', 233);
insert into Languages (lang_id, question, answer, language, questionNumber) values (357, 'el elefante', 'elephant', 'spanish', 234);
insert into Languages (lang_id, question, answer, language, questionNumber) values (358, 'el mono', 'monkey', 'spanish', 235);
insert into Languages (lang_id, question, answer, language, questionNumber) values (359, 'la mofeta', 'skunk', 'spanish', 236);
insert into Languages (lang_id, question, answer, language, questionNumber) values (360, 'águila', 'eagle', 'spanish', 237);
insert into Languages (lang_id, question, answer, language, questionNumber) values (361, 'pez', 'fish', 'spanish', 238);
insert into Languages (lang_id, question, answer, language, questionNumber) values (362, 'la ballena', 'whale', 'spanish', 239);
insert into Languages (lang_id, question, answer, language, questionNumber) values (363, 'el bosque', 'forest', 'spanish', 240);
insert into Languages (lang_id, question, answer, language, questionNumber) values (364, 'los árboles', 'trees', 'spanish', 241);
insert into Languages (lang_id, question, answer, language, questionNumber) values (365, 'planta', 'plant', 'spanish', 242);
insert into Languages (lang_id, question, answer, language, questionNumber) values (366, 'flor', 'flower', 'spanish', 243);
insert into Languages (lang_id, question, answer, language, questionNumber) values (367, 'selva', 'jungle', 'spanish', 244);
insert into Languages (lang_id, question, answer, language, questionNumber) values (368, 'el océano', 'ocean', 'spanish', 245);
insert into Languages (lang_id, question, answer, language, questionNumber) values (369, 'el río', 'river', 'spanish', 246);
insert into Languages (lang_id, question, answer, language, questionNumber) values (370, 'la charca', 'pond', 'spanish', 247);
insert into Languages (lang_id, question, answer, language, questionNumber) values (371, 'el lago', 'lake', 'spanish', 248);
insert into Languages (lang_id, question, answer, language, questionNumber) values (372, 'la colina', 'hill', 'spanish', 249);
insert into Languages (lang_id, question, answer, language, questionNumber) values (373, 'la montaña', 'mountain', 'spanish', 250);
insert into Languages (lang_id, question, answer, language, questionNumber) values (374, 'cascada', 'waterfall', 'spanish', 251);
insert into Languages (lang_id, question, answer, language, questionNumber) values (375, 'el arco iris', 'rainbow', 'spanish', 252);
insert into Languages (lang_id, question, answer, language, questionNumber) values (376, 'el cielo', 'sky', 'spanish', 253);
insert into Languages (lang_id, question, answer, language, questionNumber) values (377, 'niebla', 'cloud', 'spanish', 254);
insert into Languages (lang_id, question, answer, language, questionNumber) values (378, 'la lluvia', 'rain', 'spanish', 255);
insert into Languages (lang_id, question, answer, language, questionNumber) values (379, 'el nieve', 'snow', 'spanish', 256);
insert into Languages (lang_id, question, answer, language, questionNumber) values (380, 'el granizo', 'hail', 'spanish', 257);
insert into Languages (lang_id, question, answer, language, questionNumber) values (381, 'la niebla', 'fog', 'spanish', 258);
insert into Languages (lang_id, question, answer, language, questionNumber) values (382, 'el campo', 'field', 'spanish', 259);
insert into Languages (lang_id, question, answer, language, questionNumber) values (383, 'el relámpago', 'lightning', 'spanish', 260);
insert into Languages (lang_id, question, answer, language, questionNumber) values (384, 'el ángel', 'angel', 'spanish', 261);
insert into Languages (lang_id, question, answer, language, questionNumber) values (385, 'el bautismo', 'baptism', 'spanish', 262);
insert into Languages (lang_id, question, answer, language, questionNumber) values (386, 'la biblia', 'Bible', 'spanish', 263);
insert into Languages (lang_id, question, answer, language, questionNumber) values (387, 'el obispo', 'bishop', 'spanish', 264);
insert into Languages (lang_id, question, answer, language, questionNumber) values (388, 'el buddismo', 'Buddhism', 'spanish', 265);
insert into Languages (lang_id, question, answer, language, questionNumber) values (389, 'el catedral', 'cathedral', 'spanish', 266);
insert into Languages (lang_id, question, answer, language, questionNumber) values (390, 'el cristianismo', 'Christianity', 'spanish', 267);
insert into Languages (lang_id, question, answer, language, questionNumber) values (391, 'la iglesia', 'church', 'spanish', 268);
insert into Languages (lang_id, question, answer, language, questionNumber) values (392, 'la fe', 'faith', 'spanish', 269);
insert into Languages (lang_id, question, answer, language, questionNumber) values (393, 'el Diós', 'God', 'spanish', 270);
insert into Languages (lang_id, question, answer, language, questionNumber) values (394, 'el cielo', 'heaven', 'spanish', 271);
insert into Languages (lang_id, question, answer, language, questionNumber) values (395, 'el infierno', 'hell', 'spanish', 272);
insert into Languages (lang_id, question, answer, language, questionNumber) values (396, 'el judaismo', 'Judaism', 'spanish', 273);
insert into Languages (lang_id, question, answer, language, questionNumber) values (397, 'el monasterio', 'monastery', 'spanish', 274);
insert into Languages (lang_id, question, answer, language, questionNumber) values (398, 'el Pápa', 'Pope', 'spanish', 275);
insert into Languages (lang_id, question, answer, language, questionNumber) values (399, 'la profeta', 'prophet', 'spanish', 276);
insert into Languages (lang_id, question, answer, language, questionNumber) values (400, 'el protestante', 'Protestant', 'spanish', 277);
insert into Languages (lang_id, question, answer, language, questionNumber) values (401, 'la religión', 'religion', 'spanish', 278);
insert into Languages (lang_id, question, answer, language, questionNumber) values (402, 'el sermón', 'sermon', 'spanish', 279);
insert into Languages (lang_id, question, answer, language, questionNumber) values (403, 'el templo', 'temple', 'spanish', 280);
insert into Languages (lang_id, question, answer, language, questionNumber) values (404, 'cantar', 'to sing', 'spanish', 281);
insert into Languages (lang_id, question, answer, language, questionNumber) values (405, 'adorar', 'to worship', 'spanish', 282);
insert into Languages (lang_id, question, answer, language, questionNumber) values (406, 'orar', 'to pray', 'spanish', 283);
insert into Languages (lang_id, question, answer, language, questionNumber) values (407, 'arrepentirse', 'to repent', 'spanish', 284);
insert into Languages (lang_id, question, answer, language, questionNumber) values (408, '﻿Hallo!', 'Hi!', 'german', 1);
insert into Languages (lang_id, question, answer, language, questionNumber) values (409, 'Guten Morgen!', 'Good morning!', 'german', 2);
insert into Languages (lang_id, question, answer, language, questionNumber) values (410, 'Guten Abend!', 'Good evening!', 'german', 3);
insert into Languages (lang_id, question, answer, language, questionNumber) values (411, 'Willkommen!', 'Welcome!', 'german', 4);
insert into Languages (lang_id, question, answer, language, questionNumber) values (412, 'Wie geht''s dir/ Ihnen?', 'How are you?', 'german', 5);
insert into Languages (lang_id, question, answer, language, questionNumber) values (413, '"Danke, mir geht''s gut!"', '"I''m fine, thanks!"', 'german', 6);
insert into Languages (lang_id, question, answer, language, questionNumber) values (414, 'Und dir/Ihnen?', 'And you?', 'german', 7);
insert into Languages (lang_id, question, answer, language, questionNumber) values (415, 'Gut/ So la-la', 'Good/ So-So.', 'german', 8);
insert into Languages (lang_id, question, answer, language, questionNumber) values (416, 'Danke (vielmals)!/ Vielen Dank!', 'Thank you (very much)!', 'german', 9);
insert into Languages (lang_id, question, answer, language, questionNumber) values (417, 'Gern gescheh''n!/ Keine Ursache!/ Kein Problem!', 'You''re welcome!', 'german', 10);
insert into Languages (lang_id, question, answer, language, questionNumber) values (418, 'Hey! Kumpel! (only for male people)', 'Hey! Friend!', 'german', 11);
insert into Languages (lang_id, question, answer, language, questionNumber) values (419, 'Du hast/ Sie haben mir so gefehlt!', 'I missed you so much!', 'german', 12);
insert into Languages (lang_id, question, answer, language, questionNumber) values (420, 'Was gibt''s Neues?', 'What''s new?', 'german', 13);
insert into Languages (lang_id, question, answer, language, questionNumber) values (421, 'Nicht viel.', 'Nothing much', 'german', 14);
insert into Languages (lang_id, question, answer, language, questionNumber) values (422, 'Gute Nacht!', 'Good night!', 'german', 15);
insert into Languages (lang_id, question, answer, language, questionNumber) values (423, 'Bis später!', 'See you later!', 'german', 16);
insert into Languages (lang_id, question, answer, language, questionNumber) values (424, 'Auf Wiedersehen!/ Tschüß!', 'Good bye!', 'german', 17);
insert into Languages (lang_id, question, answer, language, questionNumber) values (425, 'Ich habe mich verlaufen!', 'I''m lost', 'german', 18);
insert into Languages (lang_id, question, answer, language, questionNumber) values (426, 'Kann ich dir/ Ihnen helfen?', 'Can I help you?', 'german', 19);
insert into Languages (lang_id, question, answer, language, questionNumber) values (427, 'Kannst du/ Können Sie mir helfen?', 'Can you help me?', 'german', 20);
insert into Languages (lang_id, question, answer, language, questionNumber) values (428, 'Wo ist (das Badezimmer/ die Apotheke?)', 'Where is the (bathroom/ pharmacy)?', 'german', 21);
insert into Languages (lang_id, question, answer, language, questionNumber) values (429, 'Gehen Sie geradeaus! Dann links / rechts abbiegen!', 'Go straight! then turn left/ right!', 'german', 22);
insert into Languages (lang_id, question, answer, language, questionNumber) values (430, 'Ich suche John.', 'I''m looking for john.', 'german', 23);
insert into Languages (lang_id, question, answer, language, questionNumber) values (431, '"Einen Augenblick, bitte!"', 'One moment please!', 'german', 24);
insert into Languages (lang_id, question, answer, language, questionNumber) values (432, '"Bleiben Sie dran, bitte!"', 'Hold on please! (phone)', 'german', 25);
insert into Languages (lang_id, question, answer, language, questionNumber) values (433, 'Was kostet das?/ Wie teuer ist das?', 'How much is this?', 'german', 26);
insert into Languages (lang_id, question, answer, language, questionNumber) values (434, 'Entschuldigen Sie bitte...!', 'Excuse me ...! (to ask for something)', 'german', 27);
insert into Languages (lang_id, question, answer, language, questionNumber) values (435, 'Darf ich mal vorbei?', 'Excuse me! ( to pass by)', 'german', 28);
insert into Languages (lang_id, question, answer, language, questionNumber) values (436, 'Kommen Sie mit!', 'Come with me!', 'german', 29);
insert into Languages (lang_id, question, answer, language, questionNumber) values (437, 'Sprechen Sie (Englisch/ Deutsch)?', 'Do you speak (English/ German)?', 'german', 30);
insert into Languages (lang_id, question, answer, language, questionNumber) values (438, 'Nur ein bißchen.', 'Just a little.', 'german', 31);
insert into Languages (lang_id, question, answer, language, questionNumber) values (439, 'Wie heißen Sie?', 'What''s your name?', 'german', 32);
insert into Languages (lang_id, question, answer, language, questionNumber) values (440, 'Ich heiße... / Mein Name ist...', 'My name is ...', 'german', 33);
insert into Languages (lang_id, question, answer, language, questionNumber) values (441, 'Herr/ Frau/ Fräulein (not used anymore)', 'Mr.../ Mrs.…/ Miss…', 'german', 34);
insert into Languages (lang_id, question, answer, language, questionNumber) values (442, '"Schön, Sie kennenzulernen!"', 'Nice to meet you!', 'german', 35);
insert into Languages (lang_id, question, answer, language, questionNumber) values (443, 'Du bist/ Sie sind sehr freundlich!', 'You''re very kind!', 'german', 36);
insert into Languages (lang_id, question, answer, language, questionNumber) values (444, 'Woher kommst du/ kommen Sie?', 'Where are you from?', 'german', 37);
insert into Languages (lang_id, question, answer, language, questionNumber) values (445, 'Ich komme (aus den U.S.A./ aus Amerika / aus Deutschland)', 'I''m from (the U.S/ Germany)', 'german', 38);
insert into Languages (lang_id, question, answer, language, questionNumber) values (446, 'Ich bin (Amerikaner)', 'I''m (American)', 'german', 39);
insert into Languages (lang_id, question, answer, language, questionNumber) values (447, 'Wo wohnst du/ wohnen Sie?', 'Where do you live?', 'german', 40);
insert into Languages (lang_id, question, answer, language, questionNumber) values (448, 'Ich wohne (in den U.S.A./ in Amerika/ in Deutschland)', 'I live in (the U.S/ Germany)', 'german', 41);
insert into Languages (lang_id, question, answer, language, questionNumber) values (449, 'Gefällt es dir/ Ihnen hier?', 'Did you like it here?', 'german', 42);
insert into Languages (lang_id, question, answer, language, questionNumber) values (450, 'Deutschland ist wunderschön', 'Germany is a wonderful country', 'german', 43);
insert into Languages (lang_id, question, answer, language, questionNumber) values (451, 'Was ist dein/ Ihr Beruf?', 'What do you do for a living?', 'german', 44);
insert into Languages (lang_id, question, answer, language, questionNumber) values (452, 'Ich bin (Übersetzer/Dolmetscher) / Geschäftsmann', 'I work as a (translator/ businessman)', 'german', 45);
insert into Languages (lang_id, question, answer, language, questionNumber) values (453, 'Ich mag Deutsch', 'I like German', 'german', 46);
insert into Languages (lang_id, question, answer, language, questionNumber) values (454, 'Ich lerne seit einem Monat Deutsch', 'I''ve been learning German for 1 month', 'german', 47);
insert into Languages (lang_id, question, answer, language, questionNumber) values (455, 'Oh! Das ist toll!', 'Oh! That''s good!', 'german', 48);
insert into Languages (lang_id, question, answer, language, questionNumber) values (456, 'Wie alt bist du/ sind Sie?', 'How old are you?', 'german', 49);
insert into Languages (lang_id, question, answer, language, questionNumber) values (457, '"Ich bin (zwanzig, dreißig,...) Jahre (alt)."', '"I''m (twenty, thirty...) years old."', 'german', 50);
insert into Languages (lang_id, question, answer, language, questionNumber) values (458, 'Ich muß gehen/ los!', 'I have to go', 'german', 51);
insert into Languages (lang_id, question, answer, language, questionNumber) values (459, 'Ich bin sofort wieder da!', 'I will be right back!', 'german', 52);
insert into Languages (lang_id, question, answer, language, questionNumber) values (460, 'Viel Glück!', 'Good luck!', 'german', 53);
insert into Languages (lang_id, question, answer, language, questionNumber) values (461, 'Alles Gute zum Geburtstag!', 'Happy birthday!', 'german', 54);
insert into Languages (lang_id, question, answer, language, questionNumber) values (462, 'Ein frohes neues Jahr!', 'Happy new year!', 'german', 55);
insert into Languages (lang_id, question, answer, language, questionNumber) values (463, 'Fröhliche Weihnachten!', 'Merry Christmas!', 'german', 56);
insert into Languages (lang_id, question, answer, language, questionNumber) values (464, '(Herzlichen) Glückwunsch!', 'Congratulations!', 'german', 57);
insert into Languages (lang_id, question, answer, language, questionNumber) values (465, 'Guten Appetit!', 'Enjoy!', 'german', 58);
insert into Languages (lang_id, question, answer, language, questionNumber) values (466, 'Ich möchte eines Tages (mal) nach Deutschland reisen', 'I''d like to visit Germany one day', 'german', 59);
insert into Languages (lang_id, question, answer, language, questionNumber) values (467, 'Grüß/ Grüßen Sie John von mir!', 'Say hi to John for me', 'german', 60);
insert into Languages (lang_id, question, answer, language, questionNumber) values (468, 'Gesundheit!', 'Bless you ', 'german', 61);
insert into Languages (lang_id, question, answer, language, questionNumber) values (469, 'Gute Nacht und träum was schönes!', 'Good night and sweet dreams!', 'german', 62);
insert into Languages (lang_id, question, answer, language, questionNumber) values (470, '"Entschuldigung, ich habe Sie nicht verstanden!"', 'I''m Sorry!', 'german', 63);
insert into Languages (lang_id, question, answer, language, questionNumber) values (471, 'Entschuldigung!/ Es tut mir leid!', 'Sorry ', 'german', 64);
insert into Languages (lang_id, question, answer, language, questionNumber) values (472, 'Kein Problem!/ Keine Ursache!', 'No Problem!', 'german', 65);
insert into Languages (lang_id, question, answer, language, questionNumber) values (473, 'Kannst du/ Können Sie das nochmal wiederholen?', 'Can You Say It Again?', 'german', 66);
insert into Languages (lang_id, question, answer, language, questionNumber) values (474, 'Kannst du/ Können Sie (etwas) langsamer sprechen?', 'Can You Speak Slowly?', 'german', 67);
insert into Languages (lang_id, question, answer, language, questionNumber) values (475, 'Schreib/ Schreiben Sie es bitte auf!', 'Write It Down Please!', 'german', 68);
insert into Languages (lang_id, question, answer, language, questionNumber) values (476, '"Ich verstehe das/ dich/ Sie nicht! (das:that, dich:you, Sie:you polite)"', 'I Don''t Understand!', 'german', 69);
insert into Languages (lang_id, question, answer, language, questionNumber) values (477, 'Ich weiß (es) nicht!', 'I Don''t Know!', 'german', 70);
insert into Languages (lang_id, question, answer, language, questionNumber) values (478, 'Ich habe keine Ahnung.', 'I Have No Idea.', 'german', 71);
insert into Languages (lang_id, question, answer, language, questionNumber) values (479, 'Wie heißt das auf deutsch?', 'What''s That Called In German?', 'german', 72);
insert into Languages (lang_id, question, answer, language, questionNumber) values (480, '"Was bedeutet ""nacht"" auf englisch?"', '"What Does ""gato"" Mean In English?"', 'german', 73);
insert into Languages (lang_id, question, answer, language, questionNumber) values (481, '"Wie sagt man ""please"" auf deutsch?"', '"How Do You Say ""Please"" In German?"', 'german', 74);
insert into Languages (lang_id, question, answer, language, questionNumber) values (482, 'Was ist das (hier)?', 'What Is This?', 'german', 75);
insert into Languages (lang_id, question, answer, language, questionNumber) values (483, 'Mein Deutsch ist schlecht.', 'My German is bad.', 'german', 76);
insert into Languages (lang_id, question, answer, language, questionNumber) values (484, 'Ich muß (mein) Deutsch üben.', 'I need to practice my German', 'german', 77);
insert into Languages (lang_id, question, answer, language, questionNumber) values (485, '(Nur) Keine Sorge!', 'Don''t worry!', 'german', 78);
insert into Languages (lang_id, question, answer, language, questionNumber) values (486, 'gut/ schlecht/ so la-la', 'Good/ Bad/ So-So', 'german', 79);
insert into Languages (lang_id, question, answer, language, questionNumber) values (487, 'groß/ klein.', 'Big/ Small', 'german', 80);
insert into Languages (lang_id, question, answer, language, questionNumber) values (488, 'heute/ jetzt', 'Today/ Now', 'german', 81);
insert into Languages (lang_id, question, answer, language, questionNumber) values (489, 'morgen/ gestern', 'Tomorrow/ Yesterday', 'german', 82);
insert into Languages (lang_id, question, answer, language, questionNumber) values (490, 'ja/ nein', 'Yes/ No', 'german', 83);
insert into Languages (lang_id, question, answer, language, questionNumber) values (491, 'Bitte sehr!/ Bitte schön!', 'Here you go! (when giving something)', 'german', 84);
insert into Languages (lang_id, question, answer, language, questionNumber) values (492, 'Gefällt''s dir/ Ihnen?', 'Do you like it?', 'german', 85);
insert into Languages (lang_id, question, answer, language, questionNumber) values (493, 'Mir gefällt es sehr gut!', 'I really like it!', 'german', 86);
insert into Languages (lang_id, question, answer, language, questionNumber) values (494, 'Ich habe Hunger/Durst.', 'I''m hungry/ thirsty.', 'german', 87);
insert into Languages (lang_id, question, answer, language, questionNumber) values (495, 'am Morgen/morgens/ am Abend/abends/ in der Nacht', 'In The Morning/ Evening/ At Night.', 'german', 88);
insert into Languages (lang_id, question, answer, language, questionNumber) values (496, 'dies(es/er/e)/ das. hier/ dort.', 'This/ That. Here/There', 'german', 89);
insert into Languages (lang_id, question, answer, language, questionNumber) values (497, 'Ich/ Du. Er/ sie', 'Me/ You. Him/ Her.', 'german', 90);
insert into Languages (lang_id, question, answer, language, questionNumber) values (498, 'Wirklich?!/ Echt?!', 'Really!', 'german', 91);
insert into Languages (lang_id, question, answer, language, questionNumber) values (499, 'Guck (mal)/ Schau (mal)!', 'Look!', 'german', 92);
insert into Languages (lang_id, question, answer, language, questionNumber) values (500, 'Beeil dich!/ beeilen Sie sich!', 'Hurry up!', 'german', 93);
insert into Languages (lang_id, question, answer, language, questionNumber) values (501, 'was?/ wo?', 'What? Where?', 'german', 94);
insert into Languages (lang_id, question, answer, language, questionNumber) values (502, 'Wieviel Uhr ist es?/ Wie spät ist es?', 'What time is it?', 'german', 95);
insert into Languages (lang_id, question, answer, language, questionNumber) values (503, 'Es ist zehn Uhr. Sieben Uhr dreißig/ halb acht.', 'It''s 10 o''clock. 07:30pm.', 'german', 96);
insert into Languages (lang_id, question, answer, language, questionNumber) values (504, 'Gib mir das!', 'Give me this!', 'german', 97);
insert into Languages (lang_id, question, answer, language, questionNumber) values (505, 'Ich liebe dich/ Sie!', 'I love you!', 'german', 98);
insert into Languages (lang_id, question, answer, language, questionNumber) values (506, 'Ich fühle mich nicht wohl.', 'I feel sick.', 'german', 99);
insert into Languages (lang_id, question, answer, language, questionNumber) values (507, 'Ich brauche einen Arzt.', 'I need a doctor', 'german', 100);
insert into Languages (lang_id, question, answer, language, questionNumber) values (508, '"eins, zwei, drei"', '"One, Two, Three"', 'german', 101);
insert into Languages (lang_id, question, answer, language, questionNumber) values (509, '"vier, fünf, sechs"', '"Four, Five, Six"', 'german', 102);
insert into Languages (lang_id, question, answer, language, questionNumber) values (510, '"sieben, acht, neun, zehn"', '"Seven, Eight, Nine, Ten"', 'german', 103);
insert into Languages (lang_id, question, answer, language, questionNumber) values (511, 'Ich suche eine Apotheke', 'I‘m looking for a pharmacy', 'german', 104);
insert into Languages (lang_id, question, answer, language, questionNumber) values (512, 'Gibt es irgendwelche Nebenwirkungen?', 'Are there any side effects?', 'german', 105);
insert into Languages (lang_id, question, answer, language, questionNumber) values (513, 'Mein Arzt sagte (mir) ...', 'My Doctor said ...', 'german', 106);
insert into Languages (lang_id, question, answer, language, questionNumber) values (514, 'Die Stunde ist ausgefallen', 'The class was canceled', 'german', 107);
insert into Languages (lang_id, question, answer, language, questionNumber) values (515, 'Meine Telefonnummer ist ...', 'My telephone number is ...', 'german', 108);
insert into Languages (lang_id, question, answer, language, questionNumber) values (516, 'Du kannst mich jederzeit anrufen', 'You can call me at any time', 'german', 109);
insert into Languages (lang_id, question, answer, language, questionNumber) values (517, 'Du kannst mir eine SMS/Textnachricht schicken', 'You can send me a text message', 'german', 110);
insert into Languages (lang_id, question, answer, language, questionNumber) values (518, 'Du kannst mir eine E-Mail schreiben', 'You can write me an E-Mail', 'german', 111);
insert into Languages (lang_id, question, answer, language, questionNumber) values (519, 'Warum ist mir das nicht eingefallen?', 'Why didn‘t I think of that?', 'german', 112);
insert into Languages (lang_id, question, answer, language, questionNumber) values (520, 'Das ist mir auch aufgefallen', '"I noticed that, too"', 'german', 113);
insert into Languages (lang_id, question, answer, language, questionNumber) values (521, 'Die Telefonrechnung ist fällig', 'The telephone bill is due', 'german', 114);
insert into Languages (lang_id, question, answer, language, questionNumber) values (522, 'Guten Appetit!', 'Enjoy the meal!', 'german', 115);
insert into Languages (lang_id, question, answer, language, questionNumber) values (523, 'Mir ist langweilig', 'I‘m bored', 'german', 116);
insert into Languages (lang_id, question, answer, language, questionNumber) values (524, 'Sei ruhig!', 'Be quiet!', 'german', 117);
insert into Languages (lang_id, question, answer, language, questionNumber) values (525, 'Verschwinde!', 'Get lost!', 'german', 118);
insert into Languages (lang_id, question, answer, language, questionNumber) values (526, 'Was hast Du?', 'What‘s wrong with you?', 'german', 119);
insert into Languages (lang_id, question, answer, language, questionNumber) values (527, 'Spinnst Du?', 'Are you crazy?', 'german', 120);
insert into Languages (lang_id, question, answer, language, questionNumber) values (528, 'Lass mich in Ruhe!', 'Leave me alone!', 'german', 121);
insert into Languages (lang_id, question, answer, language, questionNumber) values (529, 'Ich vermisse dich', 'I miss you', 'german', 122);
insert into Languages (lang_id, question, answer, language, questionNumber) values (530, 'Ich liebe dich', 'I love you', 'german', 123);
insert into Languages (lang_id, question, answer, language, questionNumber) values (531, 'Ich mag dich/Ich habe dich gern', 'I like you', 'german', 124);
insert into Languages (lang_id, question, answer, language, questionNumber) values (532, 'Hast Du morgen Abend Zeit?', 'Are you free tomorrow evening?', 'german', 125);
insert into Languages (lang_id, question, answer, language, questionNumber) values (533, 'Ich möchte Dich zum Abendessen einladen.', 'I would like to invite you to dinner', 'german', 126);
insert into Languages (lang_id, question, answer, language, questionNumber) values (534, 'Du siehst schön aus!', 'You look beautiful!', 'german', 127);
insert into Languages (lang_id, question, answer, language, questionNumber) values (535, 'Kannst Du mir mehr über Dich erzählen?', 'Can you tell me more about you?', 'german', 128);
insert into Languages (lang_id, question, answer, language, questionNumber) values (536, 'Ich bin Single', 'I‘m single', 'german', 129);
insert into Languages (lang_id, question, answer, language, questionNumber) values (537, 'Ich bin verheiratet', 'I‘m married', 'german', 130);
insert into Languages (lang_id, question, answer, language, questionNumber) values (538, 'Interessiert mich nicht!', 'I‘m not interested!', 'german', 131);
insert into Languages (lang_id, question, answer, language, questionNumber) values (539, 'Kann ich deine Telefonnummer haben?', 'Can I have your phone number?', 'german', 132);
insert into Languages (lang_id, question, answer, language, questionNumber) values (540, 'Möchtest Du spazieren gehen?', 'Would you like to go for a walk?', 'german', 133);
insert into Languages (lang_id, question, answer, language, questionNumber) values (541, 'Ich mache nur Spaß', 'I‘m just kidding', 'german', 134);
insert into Languages (lang_id, question, answer, language, questionNumber) values (542, 'Ich meine es Ernst.', 'I‘m serious', 'german', 135);
insert into Languages (lang_id, question, answer, language, questionNumber) values (543, 'Ich bin Vegetarier', 'I‘m vegetarian', 'german', 136);
insert into Languages (lang_id, question, answer, language, questionNumber) values (544, 'Ich bin ein Veganer', 'I‘m a vegan', 'german', 137);
insert into Languages (lang_id, question, answer, language, questionNumber) values (545, 'Ich esse kein Schweinefleisch!', 'I don‘t eat pork!', 'german', 138);
insert into Languages (lang_id, question, answer, language, questionNumber) values (546, 'Ich trinke keinen Alkohol', 'I don‘t drink alcohol', 'german', 139);
insert into Languages (lang_id, question, answer, language, questionNumber) values (547, 'Liebe Güte!', 'My God!', 'german', 140);
insert into Languages (lang_id, question, answer, language, questionNumber) values (548, 'Ach je!', 'Oh gosh!', 'german', 141);
insert into Languages (lang_id, question, answer, language, questionNumber) values (549, 'Mist!', 'It sucks!', 'german', 142);
insert into Languages (lang_id, question, answer, language, questionNumber) values (550, 'Das ist ein hohes Gebäude', 'That is a tall building', 'german', 143);
insert into Languages (lang_id, question, answer, language, questionNumber) values (551, 'Ich habe einen sehr alten Mann getroffen', 'I met a very old man', 'german', 144);
insert into Languages (lang_id, question, answer, language, questionNumber) values (552, 'Das alte rote Gebäude ist hier', 'The old red building is here', 'german', 145);
insert into Languages (lang_id, question, answer, language, questionNumber) values (553, 'Das ist ein sehr schönes Kleid', 'That''s a very nice dress', 'german', 146);
